Define `_PyErr_ChainExceptions()` FFI for CPython.
